import brownBagImage from "../Home/assets/product-brown-bag.jpg";
import linenShirtImage from "../Home/assets/product-linen-shirt.jpg";
import navyBlazerImage from "../Home/assets/product-navy-blazer.jpg";
import whiteSneakersImage from "../Home/assets/product-white-sneakers.jpg";

export const fallbackProductImage = linenShirtImage;

export const mockProducts = [
  {
    id: "mock-ao-linen",
    slug: "mock-ao-linen",
    name: "Áo sơ mi linen thanh lịch",
    price: 689000,
    oldPrice: 790000,
    image: linenShirtImage,
    category: "Áo sơ mi",
    description: "Chất linen nhẹ và thoáng mát cho phong cách hằng ngày.",
    rating: 4.8,
    badge: "Bán chạy",
    size: ["S", "M", "L", "XL"],
    color: ["Kem", "Trắng"],
    status: "Còn hàng",
    sold: 124,
  },
  {
    id: "mock-giay-trang",
    slug: "mock-giay-trang",
    name: "Giày thể thao trắng tối giản",
    price: 1290000,
    image: whiteSneakersImage,
    category: "Giày",
    description: "Kiểu dáng gọn gàng, dễ phối cùng nhiều trang phục.",
    rating: 4.7,
    badge: "Mới",
    size: ["38", "39", "40", "41"],
    color: ["Trắng"],
    status: "Còn hàng",
    sold: 96,
  },
  {
    id: "mock-blazer-navy",
    slug: "mock-blazer-navy",
    name: "Áo blazer xanh navy",
    price: 1590000,
    oldPrice: 1790000,
    image: navyBlazerImage,
    category: "Áo khoác",
    description: "Thiết kế may đo hiện đại dành cho phong cách công sở.",
    rating: 4.9,
    badge: "Nổi bật",
    size: ["M", "L", "XL"],
    color: ["Xanh navy"],
    status: "Còn hàng",
    sold: 142,
  },
  {
    id: "mock-tui-da",
    slug: "mock-tui-da",
    name: "Túi da nâu dáng cong",
    price: 890000,
    image: brownBagImage,
    category: "Phụ kiện",
    description: "Chất liệu da mềm với đường nét thanh lịch và tinh tế.",
    rating: 4.6,
    badge: "Yêu thích",
    color: ["Nâu"],
    status: "Còn hàng",
    sold: 78,
  },
  {
    id: "mock-ao-linen-trang",
    slug: "mock-ao-linen-trang",
    name: "Áo linen trắng phom rộng",
    price: 749000,
    image: linenShirtImage,
    category: "Áo sơ mi",
    description: "Phom rộng thoải mái, phù hợp cho ngày hè năng động.",
    rating: 4.7,
    size: ["S", "M", "L"],
    color: ["Trắng"],
    status: "Còn hàng",
    sold: 88,
  },
  {
    id: "mock-giay-kem",
    slug: "mock-giay-kem",
    name: "Giày thể thao đế kem",
    price: 1190000,
    image: whiteSneakersImage,
    category: "Giày",
    description: "Thiết kế nhẹ, êm chân với bảng màu trung tính.",
    rating: 4.5,
    size: ["38", "39", "40", "41", "42"],
    color: ["Trắng", "Kem"],
    status: "Còn hàng",
    sold: 66,
  },
  {
    id: "mock-blazer-cong-so",
    slug: "mock-blazer-cong-so",
    name: "Blazer công sở phom suông",
    price: 1690000,
    image: navyBlazerImage,
    category: "Áo khoác",
    description: "Phom suông tinh gọn, tạo vẻ ngoài chuyên nghiệp.",
    rating: 4.8,
    size: ["M", "L"],
    color: ["Xanh navy", "Đen"],
    status: "Sắp hết hàng",
    sold: 104,
  },
  {
    id: "mock-tui-vai",
    slug: "mock-tui-vai",
    name: "Túi đeo vai phong cách tối giản",
    price: 820000,
    image: brownBagImage,
    category: "Phụ kiện",
    description: "Mẫu túi nhỏ gọn dành cho những buổi dạo phố.",
    rating: 4.4,
    color: ["Nâu", "Đen"],
    status: "Còn hàng",
    sold: 54,
  },
];
